# Config WireGuard client distant (ex. télétravail)
# Importer dans l'app WireGuard (Windows/Linux/macOS)
#
# PBX gestion : 192.168.1.104
# PBX VLAN 10 : 10.10.10.10
# IP publique site : 129.0.60.188

[Interface]
PrivateKey = sCNSA5ppc2kIYkFpZ12Wscc03+pmxx1gkqJyGNgA/kE=
Address = 10.200.0.2/32
DNS = 192.168.1.1

[Peer]
PublicKey = 4GFaDEc19j1VNXeiFfnoTlsXjO6JC79ZeqzhavvWAiY=
Endpoint = 129.0.60.188:51820
AllowedIPs = 192.168.1.0/24, 10.10.10.0/24, 10.200.0.0/24
PersistentKeepalive = 25
